# Generated by Django 4.2 on 2025-10-21 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_systemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', '已计划'), ('queued', '排队中'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('cancelled', '已取消')], default='queued', max_length=20, verbose_name='状态')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='计划执行时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_manual', models.BooleanField(default=False, verbose_name='手动触发')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '任务执行',
                'verbose_name_plural': '任务执行',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('command', models.TextField(verbose_name='执行命令')),
                ('task_type', models.CharField(choices=[('one_off', '一次性任务'), ('cron', '周期任务')], default='one_off', max_length=20, verbose_name='任务类型')),
                ('cron_expression', models.CharField(blank=True, max_length=100, verbose_name='Cron表达式')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '远程执行任务',
                'verbose_name_plural': '远程执行任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionTaskTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_targets', to='assets.server', verbose_name='服务器')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='assets.executiontask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务目标服务器',
                'verbose_name_plural': '任务目标服务器',
                'ordering': ['order', 'id'],
                'unique_together': {('task', 'server')},
            },
        ),
        migrations.AddField(
            model_name='executiontask',
            name='servers',
            field=models.ManyToManyField(related_name='execution_tasks', through='assets.ExecutionTaskTarget', to='assets.server', verbose_name='目标服务器'),
        ),
        migrations.CreateModel(
            name='ExecutionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='阶段名称')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='阶段顺序')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('skipped', '跳过')], default='pending', max_length=20, verbose_name='阶段状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='assets.executionrun', verbose_name='任务执行')),
            ],
            options={
                'verbose_name': '任务阶段',
                'verbose_name_plural': '任务阶段',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='executionrun',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='assets.executiontask', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='executionrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_runs', to=settings.AUTH_USER_MODEL, verbose_name='触发人'),
        ),
        migrations.CreateModel(
            name='ExecutionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='退出码')),
                ('stdout', models.TextField(blank=True, verbose_name='标准输出')),
                ('stderr', models.TextField(blank=True, verbose_name='错误输出')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_jobs', to='assets.server', verbose_name='服务器')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='assets.executionstage', verbose_name='执行阶段')),
            ],
            options={
                'verbose_name': '服务器执行记录',
                'verbose_name_plural': '服务器执行记录',
                'ordering': ['stage__order', 'server__management_ip'],
            },
        ),
    ]
