# Generated by Django 4.2.7 on 2025-10-28 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_executionrun_executiontask_executiontasktarget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_server_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='原服务器ID')),
                ('sn', models.CharField(db_index=True, max_length=100, verbose_name='序列号')),
                ('hostname', models.CharField(blank=True, max_length=100, verbose_name='主机名')),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='状态')),
                ('ssh_username', models.CharField(blank=True, max_length=50, verbose_name='SSH用户名')),
                ('ssh_password', models.CharField(blank=True, max_length=200, verbose_name='SSH密码')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('agent_deployed', models.BooleanField(default=False, verbose_name='Agent已部署')),
                ('agent_version', models.CharField(blank=True, max_length=20, verbose_name='Agent版本')),
                ('last_report_time', models.DateTimeField(blank=True, null=True, verbose_name='最后上报时间')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(verbose_name='更新时间')),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='归档时间')),
                ('archived_reason', models.CharField(blank=True, max_length=100, verbose_name='归档原因')),
            ],
            options={
                'verbose_name': '归档服务器',
                'verbose_name_plural': '归档服务器',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedHardwareInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_info', models.JSONField(blank=True, default=dict, verbose_name='CPU信息')),
                ('memory_modules', models.JSONField(blank=True, default=list, verbose_name='内存条信息')),
                ('memory_total_gb', models.IntegerField(blank=True, null=True, verbose_name='系统总内存(GB)')),
                ('disks', models.JSONField(blank=True, default=list, verbose_name='磁盘信息')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='采集时间')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='归档时间')),
                ('archived_server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='assets.archivedserver', verbose_name='归档服务器')),
            ],
            options={
                'verbose_name': '归档硬件信息',
                'verbose_name_plural': '归档硬件信息',
            },
        ),
    ]
