# Generated by Django 4.2.7 on 2025-11-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_server_bmc_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='bmc_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, help_text='服务器BMC/IPMI地址,可为空', null=True, verbose_name='BMC IP'),
        ),
        migrations.DeleteModel(
            name='ArchivedHardwareInfo',
        ),
        migrations.DeleteModel(
            name='ArchivedServer',
        ),
    ]
