# Generated by Django 4.2.27 on 2025-12-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_server_bmc_ip_delete_archivedhardwareinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='server_base_url',
            field=models.CharField(default='http://localhost:8000', help_text='Agent上报数据的接口地址,如 http://192.168.1.100:8000', max_length=200, verbose_name='CMDB服务器地址'),
        ),
    ]
