# Generated by Django 4.2 on 2025-12-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_systemconfig_server_base_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='凭据的标识名称，如：Web服务器默认密码', max_length=100, unique=True, verbose_name='标题')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='密码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '凭据',
                'verbose_name_plural': '凭据',
                'ordering': ['-created_at'],
            },
        ),
    ]
