# Generated by Django 4.2 on 2025-12-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_credential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='description',
        ),
    ]
