# Generated by Django 4.2 on 2025-12-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_remove_credential_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='oob_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='带外密码'),
        ),
        migrations.AddField(
            model_name='server',
            name='oob_username',
            field=models.CharField(blank=True, max_length=50, verbose_name='带外用户名'),
        ),
    ]
